server:
  port: 9002

logging:
  level:
    org.springframework: info
    com.ibatis: info


spring:
  profiles:
    active: dev
  sleuth:
    enabled: true
    sampler:
      probability: 1
  zipkin:
    base-url: http://fortec-common-zipkin
    sender:
      type: web
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://mysql.forten-tech.com:3366/mscm-base?useUnicode=true&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 34821015

      initial-size: 5
      max-active: 100
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #loginByPassword-username: admin
        #loginByPassword-password: admin
      connection-properties: config.decrypt=false;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJDSTJx3OWh1q/TPdqSEpB5RrZRmcb3nGfkEqCTyEQmdcXSvuPVz2409AJMj+4u24KUchq3IhLgiXmQGfegP/rcCAwEAAQ==
      filters: stat,wall



eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    appname: fortec-mscm-base
    # 必须设置，网关路由时将依据此参数的值获取服务列表，相关连接参考：
    # com.netflix.discovery.shared.Applications.getInstancesByVirtualHostName
    virtual-host-name: fortec-mscm-base
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://${eureka.instance.hostname}:5001/eureka/

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: fortec.mscm.base.*.entity
  type-handlers-package: fortec.common.core.mybatis.handlers
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";4:"该类型为未设置主键类型",5:"字符串全局唯一ID"
    id-type: 5
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    logic-delete-value: 1
    logic-not-delete-value: 0
    #自定义SQL注入器
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector

  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true


security:
  oauth2:
    resource:
      service-id: mscm-base-service
      token-info-uri: http://localhost:5050/oauth/check_token
    client:
      client-id: upms
      # 明文密码，详情参考：org.springframework.security.oauth2.provider.token.RemoteTokenServices#getAuthorizationHeader
      client-secret: 123456
      scope:
        - upms



ignore:
  urls:
    - /lib/**
    - /scripts/**
    - /styles/**
    - /pages/**
    - //users/findByUserKey
