server:
  port: 5060

logging:
  level:
    org.springframework: info

spring:
  application:
    name: fortec-mscm-gateway
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    appname: ${spring.application.name}
    virtual-host-name: ${spring.application.name}
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://127.0.0.1:5001/eureka/

zuul:
  socket-timeout-millis: 10000
  connect-timeout-millis: 5000
  # 以下请求头不传递到下游服务器，默认 "Cookie", "Set-Cookie", "Authorization"
  sensitive-headers:
    - Set-Cookie
  ignored-patterns:
    - /**.html
    - /**.css
    - /**.js
  routes:
    # 静态资源转向配置
    static-lib-service:
      path: /lib/**
      strip-prefix: false
      service-id: fortec-mscm-portal
    static-script-service:
      path: /scripts/**
      strip-prefix: false
      service-id: fortec-mscm-portal
    static-style-service:
      path: /styles/**
      strip-prefix: false
      service-id: fortec-mscm-portal
    static-page-service:
      path: /pages/**
      strip-prefix: false
      service-id: fortec-mscm-portal
    static-example-service:
      path: /example/**
      strip-prefix: false
      service-id: fortec-mscm-portal

    upms-service:
      path: /upms/**
      serviceId: fortec-common-upms
    doc-service:
      path: /doc/**
      serviceId: fortec-common-doc
    msg-service:
      path: /msg/**
      serviceId: fortec-common-msg
    base-service:
      path: /base/**
      serviceId: fortec-mscm-base
    cert-service:
      path: /cert/**
      serviceId: fortec-mscm-cert
ribbon:
  eureka:
    enabled: true
  # 默认5秒
  ReadTimeout: 10000
